name: hammynet
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  sizer: ^2.0.15
  country_picker: ^2.0.26
  font_awesome_flutter: ^10.7.0
  pin_code_fields: ^8.0.1
  persistent_bottom_nav_bar_v2: ^5.2.3
  curved_navigation_bar: ^1.0.6
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  page_transition: ^2.1.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/categories/
    - assets/images/splashScreenImage/
      # - images/a_dot_ham.jpeg

  fonts:
    - family: UbertMoveMedium
      fonts:
        - asset: assets/fonts/UberMoveMedium.otf

    - family: UberMoveBold
      fonts:
        - asset: assets/fonts/UberMoveBold.otf
        # - asset: fonts/TrajanPro_Bold.ttf
        #   weight: 700
